<?php 
	ob_start();
	date_default_timezone_set('Asia/Manila'); 
?>
tr>
    <th colspan="13" align="center" valign="middle"><h2> Event Listing Report <?php echo $date_coverage; ?>:</h2></th>
</tr>
  <tr>
  	<th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Category </th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Title</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Starts on</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Ends on</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Location</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Details</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Available Slot</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Regular Fee</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Regular Guest Fee</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Early Bird Fee</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Early Bird Guest Fee</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Registration</th>
    <th width="10%" style="background-color:#4f81BD; color:#FFFFFF; font-size:14px;">Event Status</th>
  </tr>
  <?php foreach($events as $key=>$value): ?>
  <tr>
	<td align="left" valign="top">123</td>
  	<<td align="left" valign="top">123</td>
   <td align="left" valign="top">123</td>
   <td align="left" valign="top">123</td>
    <<td align="left" valign="top">123</td>
    <td align="left" valign="top">123</td>
    <td align="left" valign="top">
    </td>
    <td align="left" valign="top">123</td>
    <td align="left" valign="top">123</td>
    <td align="left" valign="top">123</td>
    <td align="left" valign="top">123</td>
    <td align="left" valign="top">123</td>
    <td align="left" valign="top">123</td>
  </tr>
  <?php endforeach; ?>
  <tr>
  	<td colspan="13" valign="top" align="center"><small><b>*** Nothing Follows ***</b></small></td>
  </tr>
</table>

<br />
<br />

Summary :
<table width="100%" border="0">
<tr>
    <td valign="top" align="left" width="25%">Total Record(s) Generated :</td>
    <td valign="top" align="left" width="75%">123</td>
  </tr>
<tr>
	<td align="left" valign="top" width="25%">Generated By :</td>
  	<td align="left" valign="top" width="75%">123</td>
</tr>
<tr>
	<td align="left" valign="top" width="25%">Date :</td>
  	<td align="left" valign="top" width="75%">123</td>
</tr>
</table>

<?php
	$filename ='Event_Listing_Report.xls';
	header("Content-type: application/x-msexcel"); //tried adding  charset='utf-8' into header
	header("Content-Disposition: attachment; filename=$filename");
	header("Pragma: no-cache");
	header("Expires: 0");
?>